### ISSUE TITLE
Provide a description to the repository

### ISSUE THREAD

**Issue by r03ert0** [matteogithub/scorepochs#4]
<img width="444" alt="Screenshot 2020-04-06 at 13 23 45" src="https://user-images.githubusercontent.com/2310732/78553645-e594e280-7809-11ea-9922-8f2e13c9a9ee.png">

Hello! Adding a brief description of the repository in the main page will make it easier to find. Maybe "scorEpochs: a computer aided scoring tool for resting-state M/EEG epochs" : ) ?

**Comment by matteogithub** [comment]
Thank you for the comment! A brief description added.

**Comment by r03ert0** [comment]
\o/ thank you! :D
